##This is a sample Image 
#FROM ubuntu 
#MAINTAINER demousr@gmail.com 
#
#RUN apt-get update 
#RUN apt-get install -y apt-file
#RUN apt-file update
#
#RUN apt-get install -y nginx 
#CMD [“echo”,”Image created”]
## Filename: Dockerfile 
##FROM node:10-alpine
#WORKDIR /usr/src/app
#COPY package*.json ./
#RUN npm install
#COPY . .
#EXPOSE 3000
#CMD ["npm", "start"]
FROM ubuntu 
RUN apt-get update 
RUN apt-get install -y apt-file
RUN apt-file update
RUN apt-get install -y apache2 
#RUN apt-get install -y apt-file
RUN apt-get update
RUN apt-file update
#RUN apt-get install –y apache2-utils 
RUN apt-get clean 
EXPOSE 80 CMD [“apache2ctl”, “-D”, “FOREGROUND”]
